---

driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  require_ansible_repo: true
  ansible_verbose: true
  ansible_version: latest
  require_ruby_for_busser: true
  require_chef_for_busser: false
  additional_copy_path:
    - local

transport:
  max_ssh_sessions: 6
  connection_retries: 5

busser:
  ruby_bindir: /usr/bin

platforms:
  - name: centos
    driver_config:
      box: puppetlabs/centos-7.0-64-nocm

suites:
  - name: jenkins
    provisioner:
      hosts: jenkins
