#!/usr/bin/env ruby

site "https://galaxy.ansible.com/api/v1"

role "geerlingguy.jenkins"
role "geerlingguy.java"
role "geerlingguy.ruby"
role "darkraiden.ansible-pip"
role "darkraiden.ansible-docker"
