---
  - cron:
      name: "Prune Docker files"
      minute: "0"
      hour: "0"
      job: "docker system prune --all -f"

  - cron:
      name: "Cleanup Jenkins workspace"
      minute: "30"
      hour: "0"
      job: "find {{ jenkins_home }}/workspace/* -exec rm -r \"{}\" \\;"
