---
  - name: Prune Docker files
    cron:
      name: "Prune Docker files"
      minute: "0"
      hour: "0"
      job: "docker system prune --all -f"

  - name: Clean up Jenkins workspace directory
    cron:
      name: "Clean up Jenkins workspace directory"
      minute: "30"
      hour: "0"
      job: "find {{ jenkins_home }}/workspace/* -exec rm -r \"{}\" \\;"

  - name: Clean up dead Jenkins slaves
    cron:
      name: "Clean up dead Jenkins slaves"
      minute: "0"
      hour: "*"
      job: "curl --user '{{ cc_jenkins_admin.user }}:{{ cc_jenkins_admin.token }}' --data-urlencode \"script=$(<{{ jenkins_home }}/scripts/offline_slave_cleanup.groovy)\" {{ cc_jenkins_host }}/scriptText"
