---
- name: Generate groovy startup script templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ jenkins_home }}/init.groovy.d/{{ item }}"
    owner: jenkins
    group: jenkins
  notify: restart jenkins
  with_items:
    - github_oauth.groovy
    - credentials.groovy
    - aws_credentials.groovy

- name: Ensure scripts directory exists
  file:
    path: "{{ jenkins_home }}/scripts"
    state: directory
    owner: jenkins
    group: jenkins

- name: Generate groovy cron script templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ jenkins_home }}/scripts/{{ item }}"
    owner: jenkins
    group: jenkins
  with_items:
    - offline_slave_cleanup.groovy
