---

- name: Ensure the helm directory exists
  file:
    path: /var/lib/helm
    state: directory

- name: Unarchive helm package
  unarchive:
    src: "https://storage.googleapis.com/kubernetes-helm/helm-v{{ cc_jenkins_helm_version}}-linux-amd64.tar.gz"
    dest: /tmp
    remote_src: true

  # copy module was not functioning as desired, so switched to command
- name: Copy the helm binary to /var/lib
  command: cp /tmp/{{ cc_jenkins_helm_uncompressed_dir }}/helm /var/lib/helm/helm

- name: Create link to helm binary
  file:
    src: /var/lib/helm/helm
    dest: /usr/local/bin/helm
    state: link
    force: True

- name: Remove helm temp dir
  file:
    path: "/tmp/{{ cc_jenkins_helm_uncompressed_dir }}"
    state: absent

- name: Remove helm archive file
  file:
    path: /tmp/helm.tar.gz
    state: absent

- name: Initialise helm
  become: jenkins
  command: helm init
